# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fdd4a6092a46c0b032af3fef6f63ea5bbbc0267a827fbd1ed8d275c0c2416fa3f88ee94d209b16a92fe5c9cdfd95e828cdf620c76a638feb7a67ecd2137f38ec

test:
  secret_key_base: 216b87960e4383ee9ebe0a4d9adecd4b2099a4d61b9ef9906779d8b565c2584afea22d488912fe34c54879a5ec7c64c7bacfae2366c092230885d033fafd162a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
